// Generated by scripts/generate-sub-agent-scripts.mjs. Edit the sibling .mjs files instead.

export const SubAgentFanoutScriptId = 'builtin:sub-agent/fanout';
export const SubAgentMutualReviewScriptId = 'builtin:sub-agent/mutual-review';
export const SubAgentSequentialScriptId = 'builtin:sub-agent/sequential';

export const BUILTIN_SUB_AGENT_FANOUT_SCRIPT_ID = SubAgentFanoutScriptId;
export const BUILTIN_SUB_AGENT_MUTUAL_REVIEW_SCRIPT_ID = SubAgentMutualReviewScriptId;
export const BUILTIN_SUB_AGENT_SEQUENTIAL_SCRIPT_ID = SubAgentSequentialScriptId;

export const builtinSubAgentScriptSources: Readonly<Record<string, string>> = {
  [SubAgentFanoutScriptId]: [
    '// @ts-check',
    '',
    "/** @param {import('../loop.js').SubAgentScriptContext} ctx */",
    'export default async function run(ctx) {',
    '  ctx.finishAgentResults(await ctx.runParallel());',
    '}',
  ].join('\n'),
  [SubAgentMutualReviewScriptId]: [
    '// @ts-check',
    '',
    "/** @param {import('../loop.js').SubAgentScriptContext} ctx */",
    'export default async function run(ctx) {',
    '  const drafts = await ctx.runParallel();',
    '  if (drafts.results.length < 2) {',
    '    ctx.finishAgentResults(drafts);',
    '    return;',
    '  }',
    '',
    '  const reviews = await ctx.runParallel({',
    '    agents: drafts.results.map((draft, index) => {',
    '      const reviewer = ctx.agents[(index + 1) % ctx.agents.length];',
    '      return {',
    '        ...reviewer,',
    '        prompt: [',
    "          'Review this answer against the original task.',",
    '          `Original task:\\n${ctx.input.message}`,',
    '          `Answer from ${draft.profileId}:\\n${draft.text}`,',
    "        ].join('\\n\\n'),",
    '        conversationId: `${ctx.input.conversationId}:review:${index}`,',
    '      };',
    '    }),',
    '  });',
    '',
    '  ctx.finish([',
    "    'Drafts:',",
    '    ctx.formatAgentResults(drafts, { includeFailureSection: false }),',
    "    'Reviews:',",
    '    ctx.formatAgentResults(reviews),',
    "  ].join('\\n\\n'));",
    '}',
  ].join('\n'),
  [SubAgentSequentialScriptId]: [
    '// @ts-check',
    '',
    "/** @param {import('../loop.js').SubAgentScriptContext} ctx */",
    'export default async function run(ctx) {',
    '  ctx.finishAgentResults(await ctx.runSequential());',
    '}',
  ].join('\n'),
};

export function getBuiltinSubAgentScriptSource(id: string): string | undefined {
  return builtinSubAgentScriptSources[id];
}
