// Generated by scripts/generate-loop-sources.mjs. Edit the sibling .mjs files instead.

export const AgentToolLoopDefaultScriptId = 'builtin:agent-tool-loop/default';

export const BUILTIN_AGENT_TOOL_LOOP_DEFAULT_SCRIPT_ID = AgentToolLoopDefaultScriptId;

export const builtinAgentToolLoopSources: Readonly<Record<string, string>> = {
  [AgentToolLoopDefaultScriptId]: [
    '// @ts-check',
    '',
    "/** @param {import('../../loopAPI/agent-tool-loop/loop.js').AgentToolLoopScriptContext} ctx */",
    'export default async function* run(ctx) {',
    '  const state = ctx.createState();',
    '',
    '  try {',
    '    const start = await ctx.startTurn(state);',
    '    if (start.step) yield start.step;',
    "    if (start.action === 'stop') return;",
    '',
    '    while (true) {',
    '      const result = yield* ctx.runIteration(state);',
    "      if (result.action === 'stop') return;",
    '    }',
    '  } catch (error) {',
    "    await ctx.stopTurn(state, 'error');",
    '    throw error;',
    '  } finally {',
    '    await ctx.stopTurn(state);',
    '  }',
    '}',
  ].join('\n'),
};

export function getBuiltinAgentToolLoopSource(id: string): string | undefined {
  return builtinAgentToolLoopSources[id];
}
