// Generated by scripts/generate-loop-sources.mjs. Edit the sibling .mjs files instead.

import { AgentToolLoopDefaultScriptId } from './builtinLoopSources.js';
import builtinDefault from './default.mjs';

export const builtinAgentToolLoopModules: Readonly<Record<string, unknown>> = {
  [AgentToolLoopDefaultScriptId]: { default: builtinDefault },
};

export function getBuiltinAgentToolLoopModule(id: string): unknown {
  return builtinAgentToolLoopModules[id];
}
