export type {
  AgentInstanceStore,
  AuditableAgentStorage,
  BlobStore,
  CompactionCandidatePage,
  ConversationAuditExportOptions,
  ConversationAuditExportStore,
  ConversationDirectoryStore,
  ConversationEventPage,
  ConversationEventStore,
  ConversationListPage,
  ConversationListPageCallOptions,
  ConversationListPageReset,
  ConversationListPageSuccess,
  ConversationListQuery,
  ConversationMessageCursor,
  ConversationMessageDetailRange,
  ConversationMessageIdentity,
  ConversationMessagePage,
  ConversationMessageWindowCompactionFocus,
  ConversationMessageWindowFocus,
  ConversationMessageWindowReset,
  ConversationMessageWindowResolvedFocus,
  ConversationMessageWindowResult,
  ConversationMessageWindowSuccess,
  ConversationMessageWindowTurnFocus,
  ConversationQueryMode,
  ConversationReadCallOptions,
  ConversationTimelineCompactionEntry,
  ConversationTimelineEntry,
  ConversationTimelinePage,
  ConversationTimelinePageCallOptions,
  ConversationTimelinePageReset,
  ConversationTimelinePageSuccess,
  ConversationTimelineParticipantPreview,
  ConversationTimelineParticipantRole,
  ConversationTimelineTurnEntry,
  DefinitionStore,
  FullAgentStorage,
  GetCompactionCandidatePageOptions,
  GetConversationEventPageOptions,
  GetConversationListPageOptions,
  GetConversationMessageWindowAroundOptions,
  GetConversationTimelinePageOptions,
  GetMessagePageOptions,
  GetMessagesOptions,
  GetRetainedCompactionControlsOptions,
  ImBindingStore,
  MessageVersionFrontier,
  MessageVersionFrontierCursor,
  MessageVersionFrontierPage,
  RetainedCompactionControlPage,
} from './ports.js';

export { assertAtomicAgentRetryStoreConformance, isAtomicAgentRetryStore } from './atomicAgentRetry.js';
export type { AtomicAgentRetryInput, AtomicAgentRetryResult, AtomicAgentRetryStore } from './atomicAgentRetry.js';

export {
  assertConversationMessageProjection,
  assertConversationMessageWindowResult,
  assertConversationTimelinePage,
  assertConversationTimelinePageEnvelope,
  boundConversationTimelineTurnEntry,
  buildConversationMessagePage,
  buildConversationMessageWindowAround,
  buildConversationTimelinePage,
  compareMessageCursor,
  DEFAULT_MESSAGE_PAGE_SIZE,
  MAX_CONVERSATION_MESSAGE_WINDOW_BYTES,
  MAX_CONVERSATION_MESSAGE_WINDOW_SIZE,
  MAX_CONVERSATION_TIMELINE_PAGE_BYTES,
  MAX_CONVERSATION_TIMELINE_PAGE_SIZE,
  MAX_CONVERSATION_TIMELINE_PREVIEW_LENGTH,
  MAX_MESSAGE_PAGE_SIZE,
  messageCursor,
  normalizeMessagePageLimit,
  projectConversationMessageForList,
  readConversationMessagePage,
  readConversationMessageWindowAround,
  readConversationTimelinePage,
} from './conversationPaging.js';
export type { ConversationMessageDisplayTruncation, ConversationMessageListProjection } from './conversationPaging.js';
import type { FullAgentStorage } from './ports.js';

/**
 * Monolithic storage facade (legacy shape: every port combined). Prefer the
 * narrow ports in `./ports.js` for new code so hosts can implement only the
 * capabilities they actually have.
 */
export type IAgentStorage = FullAgentStorage;
