packages:
  - "."
  - "../memeloop"
allowBuilds:
  '@ipshipyard/node-datachannel': set this to true or false
  better-sqlite3: true
  esbuild: true
  puppeteer: true
  sodium-native: true
overrides:
  memeloop-cli: 'link:'
