// Generated by scripts/generate-sub-agent-scripts.mjs. Edit the sibling .mjs files instead.

export const LlmIoDefaultScriptId = 'builtin:llm-io/default';

export const BUILTIN_LLM_IO_DEFAULT_SCRIPT_ID = LlmIoDefaultScriptId;

export const builtinLlmIoScriptSources: Readonly<Record<string, string>> = {
  [LlmIoDefaultScriptId]: [
    '// @ts-check',
    '',
    "/** @param {import('../loop.js').LlmIoScriptContext} ctx */",
    'export default async function* run(ctx) {',
    '  yield* ctx.runDefaultLoop();',
    '}',
  ].join('\n'),
};

export function getBuiltinLlmIoScriptSource(id: string): string | undefined {
  return builtinLlmIoScriptSources[id];
}
