// Generated by scripts/generate-loop-sources.mjs. Edit the sibling .mjs files instead.

import * as builtinArtifactResourceLifecycleModule from './artifact-resource-lifecycle.mjs';
import { AgentAgentLoopArtifactResourceLifecycleScriptId, AgentAgentLoopDeclarativeAgentRunScriptId, AgentAgentLoopQualityGateScriptId } from './builtinLoopSources.js';
import * as builtinDeclarativeAgentRunModule from './declarative-agent-run.mjs';
import * as builtinQualityGateModule from './quality-gate.mjs';

export const builtinAgentAgentLoopModules: Readonly<Record<string, unknown>> = {
  [AgentAgentLoopArtifactResourceLifecycleScriptId]: builtinArtifactResourceLifecycleModule,
  [AgentAgentLoopDeclarativeAgentRunScriptId]: builtinDeclarativeAgentRunModule,
  [AgentAgentLoopQualityGateScriptId]: builtinQualityGateModule,
};

export function getBuiltinAgentAgentLoopModule(id: string): unknown {
  return builtinAgentAgentLoopModules[id];
}
