// Generated by scripts/generate-loop-sources.mjs. Edit the sibling .mjs files instead.

import builtinArtifactResourceLifecycle from './artifact-resource-lifecycle.mjs';
import { AgentAgentLoopArtifactResourceLifecycleScriptId, AgentAgentLoopDeclarativeAgentRunScriptId, AgentAgentLoopQualityGateScriptId } from './builtinLoopSources.js';
import builtinDeclarativeAgentRun from './declarative-agent-run.mjs';
import builtinQualityGate from './quality-gate.mjs';

export const builtinAgentAgentLoopModules: Readonly<Record<string, unknown>> = {
  [AgentAgentLoopArtifactResourceLifecycleScriptId]: { default: builtinArtifactResourceLifecycle },
  [AgentAgentLoopDeclarativeAgentRunScriptId]: { default: builtinDeclarativeAgentRun },
  [AgentAgentLoopQualityGateScriptId]: { default: builtinQualityGate },
};

export function getBuiltinAgentAgentLoopModule(id: string): unknown {
  return builtinAgentAgentLoopModules[id];
}
